name: sadhana
description: Sadhana App and Attendance revamp

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  http: ^0.13.3
  sqflite: ^2.0.0+3
  #path_provider: ^1.1.0
  #path_provider: 0.5.0+1  #Don't Update this as getExternalStorageDir() returns getExternalStorageFileDir() of android
  path_provider: ^2.0.2
  table_calendar: ^2.3.3
  flutter_calendar_carousel: ^2.0.1
  month_picker_dialog: ^0.4.0
  csv: ^5.0.0
  #simple_permissions: ^0.1.9
  #permission: ^0.1.1
  permission_handler: ^8.0.0+2
#  permission:
#    git:
#      #url: https://github.com/devadrianapostol/permission
#      url: https://github.com/kamlesh9070/permission
  flutter_spinkit: ^5.0.0
  url_launcher: ^6.0.4
  autocomplete_textfield: ^1.7.3
  # vibration: ^1.0.2  #Comment this line for IOS
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  flutter_local_notifications: ^6.0.0
  datetime_picker_formfield: ^2.0.0
  share_extend: ^2.0.0
  android_alarm_manager: ^2.0.2
  connectivity: ^3.0.4
  package_info: ^2.0.1
  #onesignal: ^1.1.0My
#  onesignal_flutter: 2.6.3
  firebase_messaging: ^10.0.0
  firebase_core: ^1.2.0
  flutter_launcher_icons: ^0.9.0
  device_info: ^2.0.1
  flutter_cache_manager: ^3.0.2
  open_file: ^3.2.1
  charts_flutter: ^0.10.0
  json_annotation: ^4.0.1
  font_awesome_flutter: ^9.0.0
#  image_picker: ^0.7.5+3
#  image_cropper: ^1.4.0
  flutter_image_compress: ^1.0.0
  ntp: ^2.0.0
  file_picker: ^3.0.2+2
  #share:
  #  git:
  #    url: https://github.com/d-silveira/flutter-share.git

#flutter pub run build_runner build --delete-conflicting-outputs/watch                    // Convert From JSON to DART Plugin
dev_dependencies:
  build_runner: ^2.0.4
  json_serializable: ^4.1.2
  flutter_test:
    sdk: flutter

# For Android
flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon/ic_launcher.png"

# For iOS
#flutter_icons:
#  android: false
#  ios: "ic_launcher"
#  image_path: "assets/icon/launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo.png
    - images/logo_2.jpg
    - images/logo_dada.png
    - images/about_logo.jpg
    - assets/icon/calendar-icon.png
    - assets/icon/iconfinder_BT_dvd_905549.png
    - images/photo_camera.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: 'GoogleSans'
      fonts:
        - asset: fonts/GoogleSans-Medium.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
